### ISSUE TITLE
"Unable to read file" error when viewing .ascx and .cs files in the Plugins directory

### ISSUE THREAD

**Issue by leahjennings** [Triumph-Tech/magnus-vscode#2] opened 2022-10-17 13:43 UTC
In _Allowed Physical Directories_ in the Magnus settings in Rock, if I enable Plugins, I get an error when viewing any .ascx and .cs file in the Plugins directory. Spot checked several files in different sub-directories and all had the same error, unless the file was an image or a .css, .js, or .lava file. I did refresh at the server directory level and the error still occurred.
<img width="1621" alt="image" src="https://user-images.githubusercontent.com/66277785/196192853-66dda21b-243f-484f-8c29-282bff29b3a5.png">

Running this version of Visual Studio Code on macOS Monterey 12.3.1:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/66277785/196192950-93fe4494-0a28-4e96-98e7-52d36fcd2339.png">

Rock Version: Rock McKinley 13.6 (1.13.6.1)

**Comment by jonedmiston** [comment] 2022-10-17 17:28
Thanks Leia! This is being caused by IIS not allowing certain types of files (ascx, cs) from being accessed in the query string. We have a workaround where we change the file extension in the URL to work around IIS. This will be in the Magnus public beta.

**Closed as completed** 2022-10-18 15:14 UTC
Labels: bug, fixed in beta 1
